include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_dynamic_calls
    - avoid_slow_async_io
    - comment_references
    # - discarded_futures | waiting for dart 2.18
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - deprecated_consistency
    - eol_at_end_of_file
    - omit_local_variable_types
    - parameter_assignments
    - prefer_final_locals
    - prefer_foreach
    - require_trailing_commas
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_enums
    - use_named_constants

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 10
    maintainability-index: 50
    maximum-nesting-level: 5
    source-lines-of-code: 50
  rules:
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-type-name
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-match-file-name
    - prefer-moving-to-variable
    - prefer-trailing-comma
