name: feedlet
description: A Telegram bot for subscribing to RSS feeds.
version: 0.1.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  webfeed: ^0.7.0
  http: ^0.13.5
  teledart: ^0.3.4
  hive: ^2.2.3
  enough_convert: ^1.6.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.0
  hive_generator: ^1.1.3
  lints: ^2.0.0
  test: ^1.16.0
